Sign in
atlp-rwanda/Phantom-Backend-Elites pull request #13
Opened 2022-02-23 11:05 UTC by niyomozey

**Sign in to Phantom**

 **a driver and an operator** should be able to login with their credentials, so that they can perform their tasks.

**User inputs are** email and password, If one or both are incorrect the unsuccessfully attempt error message with be return as response.

**N.B: ** The right to sign in is for only user who registered in System .

2022-02-24 15:44 UTC, Anguandia requested changes

2022-02-24 15:44 UTC, Anguandia commented on src/controllers/userController.js
> +            res.statu(200).send({token: token,message:'Login successfully',project})
Please use object destructuring i.e .....send({token, project, message: 'Login successful'})

2022-02-24 15:44 UTC, Anguandia commented on src/middleware/auth.js
> +        // const token = req.header('x-auth-token');
remove commented out code through out your code-base

2022-03-04 07:02 UTC, Malaba6 requested changes
Please rebase with develop to resolve the conflicts

2022-04-12 17:20 UTC, closed without merging