Register driver operator
atlp-rwanda/Phantom-Backend-Elites pull request #18
Opened 2022-02-27 09:27 UTC by Emmanuel262

## What does this PR do?

- Create function of Register a new driver
- Create function of Register a new operator
- Check user role for allowing only administrator to do above tasks.
- Provide an errors for any unacceptable inputs depending on app functionality. 

## Description of Task to be completed?

- Implementation of Register of new driver who must provide all required information. This allows an app to check if user provided all relevant required information which must be accepted as new driver information.
- Implementation of Register of new operator who must provide all required information. This allows an app to check if user provided all relevant required information which must be accepted as new operator information.
- The functionality throw errors if there are unacceptable information provided as input fields.
- The functionality allows user to first login and then It check user status/role to see if user has privilege to perform certain task. 

## How should this be manually tested?

**Clone the repository, then type the following commands.**

- Install all dependencies:

```
    npm install
```
or 
```
    npm i
```

- start the server with
``` 
npm start
```
- Go to `http://localhost:3000/api-docs` to see API documentation of an API as starting point.
- Go to `http://localhost:3000/api/v1/register/login` to login.
- Go to `http://localhost:3000/api/v1/register/operator/` to register the new operator.
- Go to `http://localhost:3000/api/v1/register/driver/` to register the new driver.
- You must login as an admin to perform the above tasks else you will get errors. 

## Testing tools to use.

- [x] postman

## What are the relevant Trello tracker stories?

- https://trello.com/c/fcRZ3MiT/10-register-drivers-operators

2022-02-27 14:27 UTC, Malaba6 requested changes
Good job Emmanule, just a few things to change:
- I don't field validation. i.e where are you validation all the fields from? I was expecting to see a middleware that deals with validation before the request can reach the controller.

2022-02-27 14:27 UTC, Malaba6 commented on src/controllers/driverController.js
> +    const dbDriver = await User.findOne({ where: { email } });
Please make sure you query the db only after making sure the request is correct. i.e. after checking if email, firstname, lastname, etc. and all the required fields are present in the request, then you can query the db.

2022-02-27 14:27 UTC, Malaba6 commented on src/controllers/driverController.js
> +      const driver = User.build({
Why do you use the `build` method here instead of the `create` method?

2022-02-27 14:27 UTC, Malaba6 commented on src/controllers/driverController.js
> +      res.status(401).json({
The Http code for a bad request is 400, not 401. Do some reseach about the error codes.
The http code for an already existing user id 409, conflict.
This generic way of error handling that you used here does not allow you to return the right error error codes, please change that

2022-02-28 00:05 UTC, nirifabien1234 requested changes
Based on what we have agreed up on, there should be one user model for all users. As I can see, you have created a driverController and added  registerDriver and registerOperator functions inside there, which is beyond our agreements for good practices. 

I suggest to create a single userController and implement CRUD operations there, as my task will add to yours the way to differentiate users. Thank you

2022-04-01 12:49 UTC, merged