setup app to support multiple languages
atlp-rwanda/Phantom-Backend-Elites pull request #4
Opened 2022-02-16 10:18 UTC by niyomozey

**Support multiple languages**

Through using **i13m** module the user will able to interactive with the app in any languages by their choose.

2022-02-20 11:15 UTC, niyomozey commented
Now this configuration is ready to used

2022-02-21 09:20 UTC, Malaba6 requested changes
Your branch has conflicts with develop, resolve those conflicts first

2022-02-22 15:45 UTC, nirifabien1234 reviewed
Great work brother

2022-02-22 15:46 UTC, Malaba6 approved these changes

2022-02-22 15:46 UTC, merged