Add express structure and config
atlp-rwanda/Phantom-Backend-Elites pull request #9
Opened 2022-02-18 07:17 UTC by Emmanuel262

## What does this PR do?

- It add express structure especially folders.
- It provide a welcome endpoint to test setup
- Setup API documentation with Swagger
- It provide test of an endpoint provided above.

## Description of Task to be completed?

- Creating folders for each tasks for improving code maintainability and reusability.
- Provide a welcome message to the API consumers before they start consumption.
- Setup API documentation which guides API consumers how to consume an API and guidelines for starting.
- Each task and function write to complete task needs to be tested for good practice of an API.

## How should this be manually tested?

**Clone the repository, the following command to install all depandencies.**
```
    npm install
```
or 
```
    npm i
```

- start the server with `npm start`
- Go to `http://localhost:3000/` to see welcome message
- Go to `http://localhost:3000/api-docs` to see API documentation of an api.

## Testing tools to use.

---

- [x] postman

2022-02-18 09:19 UTC, cryptotearer reviewed
Incredible work brother!

2022-02-18 12:43 UTC, Malaba6 requested changes
Good job @Emmanuel262. A few things to point out though.
- First, I don't see the folders, models and controllers
- Second, you need to remove the modules folder. What it it for? You can move that file in there to models or controlers and remove it later since it's just a test file.
- third you need to put all the sequelize folders inside one folder that you can either call `db` or `sequelize` for maintainability purpose.
- Fourth, why do you have both `app.js` and `server.js`? please remove one of them, and I am thinking it `app.js`

2022-02-18 13:04 UTC, malaba6 commented on src/server.js
> +app.get("/junior", (req, res) => {
What is this endpoint for? Please remove it if it has nothing to do with the product

2022-02-18 13:04 UTC, malaba6 commented on test/home_route.js
> +const chai = require("chai");
please write es6 not es5 code here

2022-02-23 07:45 UTC, Malaba6 requested changes
There seems to be conflict with develop on this branch.
Besides github actions are failing, please make sure to fix that

2022-02-24 15:28 UTC, Anguandia requested changes

2022-02-24 15:28 UTC, Anguandia commented on test/addition.js
> +        console.log(result);
Please remove all console statments

2022-02-24 15:28 UTC, Anguandia commented on test/home_routes.js
> +// import { chai, chaiHttp, app } from "./setup.test";
Please remove code you do not need

2022-02-24 15:28 UTC, Anguandia commented on test/setup.js
> +// export { chai, chaiHttp, app, expect };
Same here

2022-02-24 17:10 UTC, merged